# Generated by CMake 2.8.6

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target vtkWrapTcl
ADD_EXECUTABLE(vtkWrapTcl IMPORTED)

# Create imported target vtkWrapTclInit
ADD_EXECUTABLE(vtkWrapTclInit IMPORTED)

# Create imported target vtkWrapPython
ADD_EXECUTABLE(vtkWrapPython IMPORTED)

# Create imported target vtkWrapPythonInit
ADD_EXECUTABLE(vtkWrapPythonInit IMPORTED)

# Create imported target vtkParseJava
ADD_EXECUTABLE(vtkParseJava IMPORTED)

# Create imported target vtkWrapJava
ADD_EXECUTABLE(vtkWrapJava IMPORTED)

# Create imported target vtksys
ADD_LIBRARY(vtksys SHARED IMPORTED)

# Create imported target vtkDICOMParser
ADD_LIBRARY(vtkDICOMParser SHARED IMPORTED)

# Create imported target vtkproj4
ADD_LIBRARY(vtkproj4 SHARED IMPORTED)

# Create imported target vtkverdict
ADD_LIBRARY(vtkverdict SHARED IMPORTED)

# Create imported target vtkmetaio
ADD_LIBRARY(vtkmetaio SHARED IMPORTED)

# Create imported target vtkexoIIc
ADD_LIBRARY(vtkexoIIc SHARED IMPORTED)

# Create imported target vtkalglib
ADD_LIBRARY(vtkalglib SHARED IMPORTED)

# Create imported target vtkEncodeString
ADD_EXECUTABLE(vtkEncodeString IMPORTED)

# Create imported target VPIC
ADD_LIBRARY(VPIC SHARED IMPORTED)

# Create imported target Cosmo
ADD_LIBRARY(Cosmo SHARED IMPORTED)

# Create imported target vtkftgl
ADD_LIBRARY(vtkftgl SHARED IMPORTED)

# Create imported target vtkCommonTCL
ADD_LIBRARY(vtkCommonTCL SHARED IMPORTED)

# Create imported target vtkCommonPythonD
ADD_LIBRARY(vtkCommonPythonD SHARED IMPORTED)

# Create imported target vtkCommonJava
ADD_LIBRARY(vtkCommonJava SHARED IMPORTED)

# Create imported target vtkCommon
ADD_LIBRARY(vtkCommon SHARED IMPORTED)

# Create imported target vtkFilteringTCL
ADD_LIBRARY(vtkFilteringTCL SHARED IMPORTED)

# Create imported target vtkFilteringPythonD
ADD_LIBRARY(vtkFilteringPythonD SHARED IMPORTED)

# Create imported target vtkFilteringJava
ADD_LIBRARY(vtkFilteringJava SHARED IMPORTED)

# Create imported target vtkFiltering
ADD_LIBRARY(vtkFiltering SHARED IMPORTED)

# Create imported target vtkImagingTCL
ADD_LIBRARY(vtkImagingTCL SHARED IMPORTED)

# Create imported target vtkImagingPythonD
ADD_LIBRARY(vtkImagingPythonD SHARED IMPORTED)

# Create imported target vtkImagingJava
ADD_LIBRARY(vtkImagingJava SHARED IMPORTED)

# Create imported target vtkImaging
ADD_LIBRARY(vtkImaging SHARED IMPORTED)

# Create imported target vtkGraphicsTCL
ADD_LIBRARY(vtkGraphicsTCL SHARED IMPORTED)

# Create imported target vtkGraphicsPythonD
ADD_LIBRARY(vtkGraphicsPythonD SHARED IMPORTED)

# Create imported target vtkGraphicsJava
ADD_LIBRARY(vtkGraphicsJava SHARED IMPORTED)

# Create imported target vtkGraphics
ADD_LIBRARY(vtkGraphics SHARED IMPORTED)

# Create imported target vtkGenericFilteringTCL
ADD_LIBRARY(vtkGenericFilteringTCL SHARED IMPORTED)

# Create imported target vtkGenericFilteringPythonD
ADD_LIBRARY(vtkGenericFilteringPythonD SHARED IMPORTED)

# Create imported target vtkGenericFilteringJava
ADD_LIBRARY(vtkGenericFilteringJava SHARED IMPORTED)

# Create imported target vtkGenericFiltering
ADD_LIBRARY(vtkGenericFiltering SHARED IMPORTED)

# Create imported target vtkIOTCL
ADD_LIBRARY(vtkIOTCL SHARED IMPORTED)

# Create imported target vtkIOPythonD
ADD_LIBRARY(vtkIOPythonD SHARED IMPORTED)

# Create imported target vtkIOJava
ADD_LIBRARY(vtkIOJava SHARED IMPORTED)

# Create imported target vtkIO
ADD_LIBRARY(vtkIO SHARED IMPORTED)

# Create imported target vtkRenderingTCL
ADD_LIBRARY(vtkRenderingTCL SHARED IMPORTED)

# Create imported target vtkRenderingPythonD
ADD_LIBRARY(vtkRenderingPythonD SHARED IMPORTED)

# Create imported target vtkRenderingJava
ADD_LIBRARY(vtkRenderingJava SHARED IMPORTED)

# Create imported target vtkRendering
ADD_LIBRARY(vtkRendering SHARED IMPORTED)

# Create imported target vtkRenderingPythonTkWidgets
ADD_LIBRARY(vtkRenderingPythonTkWidgets SHARED IMPORTED)

# Create imported target vtkVolumeRenderingTCL
ADD_LIBRARY(vtkVolumeRenderingTCL SHARED IMPORTED)

# Create imported target vtkVolumeRenderingPythonD
ADD_LIBRARY(vtkVolumeRenderingPythonD SHARED IMPORTED)

# Create imported target vtkVolumeRenderingJava
ADD_LIBRARY(vtkVolumeRenderingJava SHARED IMPORTED)

# Create imported target vtkVolumeRendering
ADD_LIBRARY(vtkVolumeRendering SHARED IMPORTED)

# Create imported target vtkHybridTCL
ADD_LIBRARY(vtkHybridTCL SHARED IMPORTED)

# Create imported target vtkHybridPythonD
ADD_LIBRARY(vtkHybridPythonD SHARED IMPORTED)

# Create imported target vtkHybridJava
ADD_LIBRARY(vtkHybridJava SHARED IMPORTED)

# Create imported target vtkHybrid
ADD_LIBRARY(vtkHybrid SHARED IMPORTED)

# Create imported target vtkWidgetsTCL
ADD_LIBRARY(vtkWidgetsTCL SHARED IMPORTED)

# Create imported target vtkWidgetsPythonD
ADD_LIBRARY(vtkWidgetsPythonD SHARED IMPORTED)

# Create imported target vtkWidgetsJava
ADD_LIBRARY(vtkWidgetsJava SHARED IMPORTED)

# Create imported target vtkWidgets
ADD_LIBRARY(vtkWidgets SHARED IMPORTED)

# Create imported target vtkParallelTCL
ADD_LIBRARY(vtkParallelTCL SHARED IMPORTED)

# Create imported target vtkParallelPythonD
ADD_LIBRARY(vtkParallelPythonD SHARED IMPORTED)

# Create imported target vtkParallelJava
ADD_LIBRARY(vtkParallelJava SHARED IMPORTED)

# Create imported target vtkParallel
ADD_LIBRARY(vtkParallel SHARED IMPORTED)

# Create imported target vtkInfovisTCL
ADD_LIBRARY(vtkInfovisTCL SHARED IMPORTED)

# Create imported target vtkInfovisPythonD
ADD_LIBRARY(vtkInfovisPythonD SHARED IMPORTED)

# Create imported target vtkInfovisJava
ADD_LIBRARY(vtkInfovisJava SHARED IMPORTED)

# Create imported target vtkInfovis
ADD_LIBRARY(vtkInfovis SHARED IMPORTED)

# Create imported target vtkGeovisTCL
ADD_LIBRARY(vtkGeovisTCL SHARED IMPORTED)

# Create imported target vtkGeovisPythonD
ADD_LIBRARY(vtkGeovisPythonD SHARED IMPORTED)

# Create imported target vtkGeovisJava
ADD_LIBRARY(vtkGeovisJava SHARED IMPORTED)

# Create imported target vtkGeovis
ADD_LIBRARY(vtkGeovis SHARED IMPORTED)

# Create imported target vtkViewsTCL
ADD_LIBRARY(vtkViewsTCL SHARED IMPORTED)

# Create imported target vtkViewsPythonD
ADD_LIBRARY(vtkViewsPythonD SHARED IMPORTED)

# Create imported target vtkViewsJava
ADD_LIBRARY(vtkViewsJava SHARED IMPORTED)

# Create imported target vtkViews
ADD_LIBRARY(vtkViews SHARED IMPORTED)

# Create imported target vtkQtChart
ADD_LIBRARY(vtkQtChart SHARED IMPORTED)

# Create imported target QVTK
ADD_LIBRARY(QVTK SHARED IMPORTED)

# Create imported target vtkChartsTCL
ADD_LIBRARY(vtkChartsTCL SHARED IMPORTED)

# Create imported target vtkChartsPythonD
ADD_LIBRARY(vtkChartsPythonD SHARED IMPORTED)

# Create imported target vtkChartsJava
ADD_LIBRARY(vtkChartsJava SHARED IMPORTED)

# Create imported target vtkCharts
ADD_LIBRARY(vtkCharts SHARED IMPORTED)

# Create imported target vtk
ADD_EXECUTABLE(vtk IMPORTED)

# Create imported target pvtk
ADD_EXECUTABLE(pvtk IMPORTED)

# Create imported target vtkPythonCore
ADD_LIBRARY(vtkPythonCore SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/VTKTargets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
